cask_args appdir: '/Applications'
tap 'caskroom/cask'

cask 'vlc'
cask 'google-earth-pro'
cask 'caffeine'
cask 'flux'
cask 'daisydisk'
cask 'transmission'
cask 'gitx'
cask 'dropbox'
cask 'slack'
cask 'sequel-pro'
cask 'textmate'
cask 'atom'
cask 'google-chrome'

brew 'homebrew/versions/mysql55', restart_service: true
brew 'wget'
brwe 'heroku'
